### ISSUE TITLE
Issues with AWS FPGA Binary file generation

### ISSUE THREAD

**Issue by belegent** [cornell-zhang/rosetta#4]
Can we use the "create_sdaccel_afi.sh" which is provided by AWS to generate the AWS FPGA Binary file? I found that when I used this script to generate awsxclbin file,  the output split file would run out of the disk then the generation process would fail due to the above reason.

**Comment by zhouyuan1119** [comment]
In our experiments we also use the script you mentioned to generate the AWS FPGA binary file, but we did not run into any disk space issue. Can you double check if you allocated enough disk space for the EC2 instance you are using?

**Comment by belegent** [comment]
> In our experiments we also use the script you mentioned to generate the AWS FPGA binary file, but we did not run into any disk space issue. Can you double check if you allocated enough disk space for the EC2 instance you are using?

I have reserved 100G disk space. It will still run out of my disk.

**Comment by zhouyuan1119** [comment]
Okay. Let me first try to reproduce this problem. Which benchmark are you using?

**Comment by belegent** [comment]
Spam filter.

**Comment by belegent** [comment]
It seems that I have made wrong compilation steps. It works now! Thanks anyway.

**Comment by zhouyuan1119** [comment]
You are welcome.
