### ISSUE TITLE
Undeclared outer_pixel_t, vel_pixel_t, as well as frames_t in optical flow's header file.

### ISSUE THREAD

**Issue by belegent** [cornell-zhang/rosetta#5]
I tried to compile the Optical Flow program in OpenCL mode. But the declarations are not complete in the header file (typedefs.h) for OpenCL mode. Can someone check the declarations and update the header file? Thank you.

**Comment by zhouyuan1119** [comment]
Sorry for the late response. I made some quick fix and it compiled on our server. Please try it out.

**Comment by zhouyuan1119** [comment]
Closed due to inactivity.
