### ISSUE TITLE
3d-rendering sw result is different from output_golden.txt

### ISSUE THREAD

**Issue by yu-zou** [cornell-zhang/rosetta#8]
Hope this repo still alive...

When we compile the 3d-rending app, sw result by running "make sw" is different from output_golden.txt.
However, the Vitis C simulation is exactly the same as output_golden.txt.

Is it possible that sw implementation has a hidden bug?
Because I notice that sw and ocl implementation use two different sets of data types by using #define.

Thank you.
Yu

**Comment by hj424** [comment]
Thank you very much for pointing out this issue! The problem is caused by a mismatched input 3D model and the golden output. We have fixed it in our latest commit, please check it out.

Thanks,
Hanchen
